### ISSUE TITLE
Provide sane default for limit settings

### ISSUE THREAD

**Issue by sanduhrs** [Insasse/comment_limit#3]
In comment_limit.module Lines 42ff., 56ff. and 131ff. the default value in getThirdPartySetting() (third parameter) is set to FALSE.
0 would be more sane and reduce the code.

**Comment by DiDebru** [comment]
Done in https://github.com/Insasse/comment_limit/commit/b145e542c3fd4288fa91856c0945d385c09e8480

Thank you for reviewing.
