### ISSUE TITLE
Wording change from translateable to translatable

### ISSUE THREAD

**Issue by sanduhrs** [Insasse/comment_limit#7]
In class CommentLimit the @return of getMessage() is documented as:

> Returns translateable markup with the correct error message.

Please change to:

> Returns translatable markup with the correct error message.

**Comment by DiDebru** [comment]
Done in https://github.com/Insasse/comment_limit/commit/35c18fa6b0ca130b2cf8145a805e776e90cab3fe

Thank you for reviewing.
