### ISSUE TITLE
Correct return value documentation

### ISSUE THREAD

**Issue by sanduhrs** [Insasse/comment_limit#8]
In class CommentLimit the @return of getFieldConfig() is documented as:

> \Drupal\Core\Entity\EntityInterface|null|static

really should be:

> \Drupal\field\Entity\FieldConfig

**Comment by DiDebru** [comment]
Done in **https://github.com/Insasse/comment_limit/commit/a149abf52d5bae6ef57734009e265b5bf66210c4**

Thank you for reviewing.
